//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryRegistrationInfoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int Id { get; set; }
        public int RecruitId { get; set; }
        public int WorkerId { get; set; }
        public System.DateTime DateAction { get; set; }
        public string Method { get; set; }
        public string Result { get; set; }
    
        public virtual Recruit Recruit { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
