//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryRegistrationInfoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketa
    {
        public int id { get; set; }
        public int RecruitId { get; set; }
        public string Subjects { get; set; }
        public string Progress { get; set; }
        public string Courses { get; set; }
        public string Sports { get; set; }
        public string Concurs { get; set; }
        public string KindTask { get; set; }
        public string ExecTask1 { get; set; }
        public string ExecTask2 { get; set; }
        public bool IsSickList { get; set; }
        public bool IsDiffAction { get; set; }
        public string DiffRel { get; set; }
        public string DiffRules { get; set; }
        public string DiffBehavior { get; set; }
        public string DiffOther { get; set; }
        public string ActivityInGroup { get; set; }
        public string PlaceInGroup { get; set; }
        public string Skills { get; set; }
        public string Reaction { get; set; }
        public string Emotion { get; set; }
        public string Traits { get; set; }
        public string RelAlco { get; set; }
        public string RelDrug { get; set; }
        public string ProfAction { get; set; }
        public string PrepareMilitary { get; set; }
    
        public virtual Recruit Recruit { get; set; }
    }
}
