//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryRegistrationInfoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalConclusion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalConclusion()
        {
            this.RecruitСommission = new HashSet<RecruitСommission>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDRecruit { get; set; }
        public string TherapistConclusion { get; set; }
        public string SurgeonConclusion { get; set; }
        public string NeurologistConclusion { get; set; }
        public string PsychiatristConclusion { get; set; }
        public string OptometristConclusion { get; set; }
        public string OtolaryngologistConclusion { get; set; }
        public string DentistConclusion { get; set; }
        public Nullable<System.DateTime> DateOfMedicalExamination { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecruitСommission> RecruitСommission { get; set; }
        public virtual Recruit Recruit { get; set; }
    }
}
