//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryRegistrationInfoSystem.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilitaryRegistrationEntities : DbContext
    {
        public MilitaryRegistrationEntities()
            : base("name=MilitaryRegistrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Anketa> Anketa { get; set; }
        public virtual DbSet<Commissar> Commissar { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<HealthCategory> HealthCategory { get; set; }
        public virtual DbSet<Learning> Learning { get; set; }
        public virtual DbSet<MedicalConclusion> MedicalConclusion { get; set; }
        public virtual DbSet<MethodLearning> MethodLearning { get; set; }
        public virtual DbSet<Recruit> Recruit { get; set; }
        public virtual DbSet<RecruitEducation> RecruitEducation { get; set; }
        public virtual DbSet<ResultLearning> ResultLearning { get; set; }
        public virtual DbSet<Summons> Summons { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Voenkomat> Voenkomat { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
    }
}
