//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryRegistrationInfoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitСommission
    {
        public int ID { get; set; }
        public int IDRecruit { get; set; }
        public int IDMedicalConclusion { get; set; }
        public System.DateTime DateOfDecisionHelthGroup { get; set; }
        public int IDGroupHealth { get; set; }
    
        public virtual GroupHealth GroupHealth { get; set; }
        public virtual MedicalConclusion MedicalConclusion { get; set; }
        public virtual Recruit Recruit { get; set; }
    }
}
