//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryRegistrationInfoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecruitEducation
    {
        public int ID { get; set; }
        public int IDRecruit { get; set; }
        public int IDEducation { get; set; }
        public string CourseOfStudy { get; set; }
        public string Faculty { get; set; }
        public bool Finished { get; set; }
    
        public virtual Education Education { get; set; }
        public virtual Recruit Recruit { get; set; }
    }
}
