//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryRegistrationInfoSystem.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summons
    {
        public int ID { get; set; }
        public int IDRecruit { get; set; }
        public int IDVoenkomat { get; set; }
        public System.DateTime DateVisiting { get; set; }
        public string MailingAddres { get; set; }
        public string ReasonForVisiting { get; set; }
    
        public virtual Recruit Recruit { get; set; }
        public virtual Voenkomat Voenkomat { get; set; }
    }
}
